<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\node\NodeInterface;
use Drupal\og\Og;

/**
 * Implements hook_ENTITY_TYPE_view for nodes.
 */
function og_join_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode) {
    dpm(Drupal::routeMatch()->getParameters()->keys());
    $entity_node_id = 'node';
    $bundle = $node->getType();
    dpm(Og::isGroup($entity_node_id, $bundle));
    $form = \Drupal::formBuilder()->getForm('Drupal\og_join\Form\OgJoinForm');
    dpm($form);
}